#Tensor


In [ ]:
import torch

In [ ]:
#从已有矩阵转化为张量
print(torch.tensor([5.5, 3.2]))

tensor([5.5000, 3.2000])


In [ ]:
# 这个是用来生成一个为未初始化的5*3的张量，切记不是全零
print(torch.empty(5, 3))

tensor([[ 0.1496,  0.9377, -1.3706],
        [-1.8573,  1.7874, -0.5040],
        [ 0.3557,  0.3984,  0.0616],
        [-0.0474, -0.9266, -1.5545],
        [-0.2086,  0.1188, -0.5464]])


In [ ]:
# 这个是生成一个均匀分布的初始化的，每个元素从0~1的张量，
print(torch.rand(5, 3))

tensor([[0.9584, 0.1837, 0.5320],
        [0.7223, 0.1257, 0.1990],
        [0.9636, 0.9487, 0.4243],
        [0.2303, 0.1915, 0.5227],
        [0.1292, 0.8817, 0.0769]])


In [ ]:
# 另外，还有其它的随机张量生成函数，如，分别是标准正态分布，离散正态分布

#标准正态分布
#torch.normal(A, B ,size(C, D), requires_grad=True)
print(torch.randn(5,3)) 

#离散正态分布
#torch.normal(A, B ,size(C, D), requires_grad=True)
print(torch.normal(1,0.5,(5,3)))

tensor([[ 1.0869, -0.3379,  0.1597],
        [ 0.6697,  0.7095,  1.3215],
        [ 0.2934, -0.7937,  0.2163],
        [-0.8328, -0.4740, -0.4225],
        [-0.8890,  1.6176,  0.3179]])
tensor([[1.0396, 1.2248, 0.8010],
        [0.8727, 0.8931, 0.8677],
        [1.6406, 0.5206, 0.4740],
        [2.0873, 1.5374, 0.1397],
        [0.7964, 2.0700, 1.6596]])


In [ ]:
# 这个是初始化一个全零张量，可以指定每个元素的类型。
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
# 全一张量
print(torch.ones(5,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# 创建一个形状和x一样，里面全是1的张量
y = torch.ones_like(x)
print(y)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [ ]:
# 创建一个形状和x一样，每个元素随机的张量
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.0710, 0.0897, 0.7569],
        [0.8559, 0.0118, 0.4946],
        [0.1315, 0.1092, 0.3220],
        [0.3196, 0.6659, 0.4696],
        [0.8902, 0.0434, 0.6166]])


In [ ]:
# 修改张量的shape
x = torch.randn(4, 4)


y = x.view(-1)
y1 = x.view(16)
print(y.shape)
print(y1.shape)

# -1的作用是让这个维度的值取决于其他维度（最后决定）
z = x.view(2, 2,-1)
z1 = x.view(2, 2, 4)
print(z.shape)
print(z1.shape)

torch.Size([16])
torch.Size([16])
torch.Size([2, 2, 4])
torch.Size([2, 2, 4])


In [ ]:
# 在指定dim出插入1维度
x = torch.zeros([2,3])
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
print(x.unsqueeze(2).shape)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


In [ ]:
# 在指定dim出删除1维（当且仅当dim处值为1才有效）
x = torch.zeros([1,2,3,1])
print(x.squeeze(0).shape)
print(x.squeeze(1).shape)
print(x.squeeze(2).shape)
print(x.squeeze(3).shape)

torch.Size([2, 3, 1])
torch.Size([1, 2, 3, 1])
torch.Size([1, 2, 3, 1])
torch.Size([1, 2, 3])
