In [1]:
import torch

In [2]:
#从已有矩阵转化为张量
print(torch.tensor([5.5, 3.2]))

tensor([5.5000, 3.2000])


In [3]:
# 这个是用来生成一个为未初始化的5*3的张量，切记不是全零
print(torch.empty(5, 3))

tensor([[ 0.0000e+00,  1.5846e+29, -1.8350e+09],
        [ 2.0005e+00, -8.3587e+19,  4.5755e-41],
        [-8.4267e+19,  4.5755e-41, -8.3909e+19],
        [ 4.5755e-41, -8.3909e+19,  4.5755e-41],
        [-1.6764e+29,  4.5755e-41, -1.7063e+29]])


In [4]:
# 这个是生成一个均匀分布的初始化的，每个元素从0~1的张量，
print(torch.rand(5, 3))

tensor([[0.2799, 0.6685, 0.3923],
        [0.5928, 0.4193, 0.4043],
        [0.8728, 0.5172, 0.8348],
        [0.3985, 0.8437, 0.2077],
        [0.6926, 0.2033, 0.1708]])


In [5]:
# 另外，还有其它的随机张量生成函数，如，分别是标准正态分布，离散正态分布

#标准正态分布
#torch.normal(A, B ,size(C, D), requires_grad=True)
print(torch.randn(5,3)) 

#离散正态分布
#torch.normal(A, B ,size(C, D), requires_grad=True)
print(torch.normal(1,0.5,(5,3)))

tensor([[-1.4553,  0.1593,  0.2066],
        [-1.6084, -0.3796,  0.3909],
        [ 0.3753, -0.9722,  0.4694],
        [ 0.3931,  1.6018,  1.4046],
        [ 0.8020,  0.8427, -1.2993]])
tensor([[0.6766, 0.7906, 0.8387],
        [0.7158, 1.1844, 1.0028],
        [1.1309, 1.0851, 1.3367],
        [1.5368, 1.4155, 1.0650],
        [0.5748, 1.9145, 1.6714]])


In [6]:
# 这个是初始化一个全零张量，可以指定每个元素的类型。
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# 全一张量
print(torch.ones(5,3))

# 创建一个形状和x一样，里面全是1的张量
y = torch.ones_like(x)
print(y)

# 创建一个形状和x一样，每个元素随机的张量
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0.5551, 0.1802, 0.6126],
        [0.4063, 0.2422, 0.1208],
        [0.6385, 0.0547, 0.9422],
        [0.6098, 0.4929, 0.5193],
        [0.1668, 0.0810, 0.1012]])


In [7]:
# 修改张量的shape
x = torch.randn(4, 4)


y = x.view(-1)
y1 = x.view(16)
print(y.shape)
print(y1.shape)

# -1的作用是让这个维度的值取决于其他维度（最后决定）
z = x.view(2, 2,-1)
z1 = x.view(2, 2,-1)
print(z.shape)
print(z1.shape)

torch.Size([16])
torch.Size([16])
torch.Size([2, 2, 4])
torch.Size([2, 2, 4])


从已有矩阵转化为张量

In [8]:
# 在指定dim出插入1维度
x = torch.zeros([2,3])
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
print(x.unsqueeze(2).shape)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


In [9]:
# 在指定dim出删除1维（当且仅当dim处值为1才有效）
x = torch.zeros([1,2,3,1])
print(x.squeeze(0).shape)
print(x.squeeze(1).shape)
print(x.squeeze(2).shape)
print(x.squeeze(3).shape)

torch.Size([2, 3, 1])
torch.Size([1, 2, 3, 1])
torch.Size([1, 2, 3, 1])
torch.Size([1, 2, 3])
